export enum EncodingScheme {
    NRZ_L = "NRZ_L",
    NRZ_I = "NRZ_I",
    BIPOLAR_AMI = "BIPOLAR_AMI",
    PSEUDOTERNARY = "PSEUDOTERNARY",
    MANCHESTER = "MANCHESTER",
    DIFFERENTIAL_MANCHESTER = "DIFFERENTIAL_MANCHESTER"
};